# Generated by Django 5.1.8 on 2025-04-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='phone',
        ),
    ]
