# Generated by Django 5.1.6 on 2025-02-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_ordermodels_manager'),
        ('groups', '0002_alter_groupmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodels',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='groups.groupmodel'),
        ),
    ]
