# Generated by Django 5.1.5 on 2025-01-28 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_ordermodels_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodels',
            name='alreadyPaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
