# Generated by Django 5.1.5 on 2025-01-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_ordermodels_alreadypaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodels',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='ordermodels',
            name='utm',
        ),
    ]
