# Generated by Django 5.1.6 on 2025-03-26 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_commentmodels_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodels',
            name='course',
            field=models.CharField(choices=[('FX', 'Forex Trading'), ('QACX', 'QA Course'), ('JCX', 'Java Course'), ('JSCX', 'JavaScript Course'), ('FE', 'Frontend Development'), ('PCX', 'Python Course')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator("^[A-ZА-ЯІЇЄҐ][a-zа-яіїєґ'-]{1,49}$", "Ім'я має починатися з великої літери та містити лише літери, апостроф або дефіс.")]),
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='sum',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
