# Generated by Django 5.1.6 on 2025-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_ordermodels_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodels',
            name='group',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
