# Generated by Django 5.1.7 on 2025-03-31 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_ordermodels_course_alter_ordermodels_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodels',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='course',
            field=models.CharField(choices=[('FX', 'Fx'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\+380\\d{9}$', 'Номер телефону має бути у форматі +380XXXXXXXXX (9 цифр після +380).')]),
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='surname',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator("^[A-ZА-ЯІЇЄҐ][a-zа-яіїєґ'-]{1,25}$", 'Прізвище має починатися з великої літери та містити лише літери, апостроф або дефіс.')]),
        ),
    ]
