# Generated by Django 5.2.2 on 2025-07-06 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_ordermodels_age_alter_ordermodels_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodels',
            old_name='text',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='alreadyPaid',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='course',
            field=models.CharField(choices=[('FS', 'Fs'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodels',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
