# Generated by Django 5.2.2 on 2025-07-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_rename_text_commentmodels_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodels',
            old_name='author',
            new_name='manager',
        ),
    ]
