# Generated by Django 5.1.5 on 2025-01-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_role_type_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role_type',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('MANAGER', 'Manager'), ('OWNER', 'Owner')], default='OWNER', max_length=20),
        ),
    ]
