# Generated by Django 5.1.5 on 2025-01-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role_type',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('MANAGER', 'Manager')], default='MANAGER', max_length=20),
        ),
    ]
