# Generated by Django 5.1.5 on 2025-01-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, )),
                ('surname', models.CharField(max_length=25, )),
                ('email', models.EmailField(max_length=100, )),
                ('phone', models.CharField(max_length=12, )),
                ('age', models.IntegerField()),
                ('course', models.CharField(
                    choices=[('FX', 'Fx'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'),
                             ('PCX', 'Pcx')], max_length=10, )),
                ('course_format',
                 models.CharField(choices=[('static', 'Static'), ('online', 'Online')], max_length=15, )),
                ('course_type', models.CharField(
                    choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'),
                             ('vip', 'Vip')], max_length=100, )),
                ('sum', models.IntegerField()),
                ('alreadyPaid', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('utm', models.CharField(max_length=100, )),
                ('msg', models.CharField(max_length=100, )),
                ('status', models.CharField(
                    choices=[('InWork', 'InWork'), ('New', 'New'), ('Aggre', 'Aggre'), ('Disaggre', 'Disaggre'),
                             ('Dubing', 'Dubing')], max_length=15, )),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
