# Generated by Django 5.1.5 on 2025-01-21 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('course', models.CharField(choices=[('FX', 'Fx'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=20)),
                ('course_type', models.CharField(choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'Vip')], max_length=20)),
                ('course_format', models.CharField(choices=[('static', 'Static'), ('online', 'Online')], max_length=20)),
                ('status', models.CharField(choices=[('InWork', 'InWork'), ('New', 'New'), ('Aggre', 'Aggre'), ('Disaggre', 'Disaggre'), ('Dubing', 'Dubing')], max_length=20)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alreadyPaid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
