# Generated by Django 5.1.5 on 2025-01-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodels',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
