# Generated by Django 5.1.5 on 2025-01-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_ordermodels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodels',
            options={'ordering': ['-id']},
        ),
    ]
