# Generated by Django 5.1.6 on 2025-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
